In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
car_df = pd.read_csv("/content/car_age_price (1).csv")

In [3]:
car_df.head()

   Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [4]:
car_df.shape

(112, 2)

In [5]:
car_df.duplicated().sum()

np.int64(54)

In [6]:
car_df = car_df.drop_duplicates()

In [7]:
car_df.shape

(58, 2)

In [8]:
# check correlation

car_df.corr()

           Year     Price
Year   1.000000  0.807276
Price  0.807276  1.000000

In [9]:
# Feature target splitting

y =car_df['Price']
x =car_df.drop('Price',axis=1)

In [10]:
y

0      465000
1      755000
2      700000
5      350000
6      425000
7      575000
8      509999
10     500000
11     500000
12     500000
13     600000
14     475000
17     550000
22     434999
30     650000
34     450000
37     486000
38     475000
39     545000
40     525000
42     550000
43     550000
45     450000
48     396000
49     600000
50     325000
52     345000
54     525000
56     341000
58     450000
59     550000
60     490000
61     540000
63     595000
65     495000
67     400000
68     465000
69     300000
70     450000
71     490000
73     320000
77     325000
78     409999
80     390000
81     390000
83     480000
85     320000
86     520000
97     640000
98     700000
99     600000
100    350000
103    375000
104    400000
107    375000
108    300000
109    425000
110    420000
Name: Price, dtype: int64

In [11]:
x

     Year
0    2018
1    2019
2    2019
5    2015
6    2016
7    2017
8    2017
10   2019
11   2018
12   2017
13   2019
14   2017
17   2017
22   2015
30   2019
34   2017
37   2017
38   2018
39   2020
40   2019
42   2018
43   2019
45   2018
48   2016
49   2018
50   2013
52   2013
54   2017
56   2014
58   2014
59   2016
60   2015
61   2017
63   2017
65   2017
67   2015
68   2015
69   2015
70   2015
71   2017
73   2013
77   2015
78   2015
80   2015
81   2014
83   2017
85   2015
86   2017
97   2020
98   2020
99   2020
100  2016
103  2017
104  2014
107  2016
108  2014
109  2015
110  2016

In [12]:
# train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42)

In [13]:
# create linear regression model

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [14]:
model = lr.fit(x_train,y_train)

In [15]:
y_pred = model.predict(x_test)

In [16]:
y_test

0      465000
7      575000
65     495000
22     434999
81     390000
103    375000
69     300000
50     325000
85     320000
17     550000
97     640000
5      350000
Name: Price, dtype: int64

In [17]:
y_pred

array([541975.77419354, 498094.31397849, 498094.31397849, 410331.39354838,
       366449.93333334, 498094.31397849, 410331.39354838, 322568.47311828,
       410331.39354838, 498094.31397849, 629738.69462365, 410331.39354838])

In [18]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

4578558064.883415
0.5952655854274035

In [19]:
year_2022 = pd.DataFrame({'Year': [2022]})

price_2022_linear = model.predict(year_2022)

print("Predicted price of a 2022 model:")
print(price_2022_linear[0])

Predicted price of a 2022 model:
717501.615053758

Lasso regession

In [23]:
from sklearn.linear_model import Lasso

In [26]:
lasso_model = Lasso(alpha=1.0)

lasso_model.fit(x_train, y_train)

print("Lasso Regression model trained successfully")

Lasso Regression model trained successfully

In [28]:
print("Lasso coefficient:")
print(lasso_model.coef_)

print("\nLasso intercept:")
print(lasso_model.intercept_)

Lasso coefficient:
[43881.17580645]

Lasso intercept:
-88010237.37419356

In [29]:
y_pred_lasso = lasso_model.predict(x_test)

print("Lasso predicted prices:")
print(y_pred_lasso)

Lasso predicted prices:
[541975.40322579 498094.22741935 498094.22741935 410331.87580645
 366450.69999999 498094.22741935 410331.87580645 322569.52419354
 410331.87580645 498094.22741935 629737.75483871 410331.87580645]

In [30]:
price_2022_lasso = lasso_model.predict(year_2022)

print("Predicted price of 2022 model using Lasso:")
print(price_2022_lasso[0])

Predicted price of 2022 model using Lasso:
717500.1064516008

Both models are same